[project]
name = "fhir-migrations"
requires-python = "==3.*"
dependencies = ["flask==1.1.2"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []
